"""add remote_stream to camera

Revision ID: fbbcf20dc627
Revises: c1d155fdc075
Create Date: 2026-06-07 05:28:24.354397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbcf20dc627'
down_revision = 'c1d155fdc075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_stream', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_column('remote_stream')

    # ### end Alembic commands ###
